// GENERATED by scripts/generate-protocol-registry.mjs — do not edit by hand.
// Top DeFi protocols from DefiLlama (api.llama.fi/protocols) by TVL, excluding
// CEX/Chain/Bridge/Infra. 110 protocols, 179 lookup keys.

export interface ProtocolRegistryEntry {
  /** Clean brand name, e.g. "Aave". */
  name: string;
  /** DefiLlama slug for the icon CDN. */
  slug: string;
}

export const PROTOCOL_REGISTRY: Record<string, ProtocolRegistryEntry> = {
  lido: {
    name: "Lido",
    slug: "lido",
  },
  aavev3: {
    name: "Aave",
    slug: "aave-v3",
  },
  aave: {
    name: "Aave",
    slug: "aave-v3",
  },
  morphoblue: {
    name: "Morpho",
    slug: "morpho-blue",
  },
  morpho: {
    name: "Morpho",
    slug: "morpho-blue",
  },
  binancestakedeth: {
    name: "Binance staked ETH",
    slug: "binance-staked-eth",
  },
  binance: {
    name: "Binance staked ETH",
    slug: "binance-staked-eth",
  },
  eigencloud: {
    name: "EigenCloud",
    slug: "eigencloud",
  },
  skylending: {
    name: "Sky",
    slug: "sky-lending",
  },
  sky: {
    name: "Sky",
    slug: "sky-lending",
  },
  sparklend: {
    name: "SparkLend",
    slug: "sparklend",
  },
  etherfistake: {
    name: "ether.fi Stake",
    slug: "ether.fi-stake",
  },
  etherfi: {
    name: "ether.fi Stake",
    slug: "ether.fi-stake",
  },
  ethenausde: {
    name: "Ethena USDe",
    slug: "ethena-usde",
  },
  ethena: {
    name: "Ethena USDe",
    slug: "ethena-usde",
  },
  justlendv1: {
    name: "JustLend",
    slug: "justlend-v1",
  },
  justlend: {
    name: "JustLend",
    slug: "justlend-v1",
  },
  blackrockbuidl: {
    name: "BlackRock BUIDL",
    slug: "blackrock-buidl",
  },
  blackrock: {
    name: "BlackRock BUIDL",
    slug: "blackrock-buidl",
  },
  arbitrumbridge: {
    name: "Arbitrum Bridge",
    slug: "arbitrum-bridge",
  },
  arbitrum: {
    name: "Arbitrum Bridge",
    slug: "arbitrum-bridge",
  },
  babylonprotocol: {
    name: "Babylon Protocol",
    slug: "babylon-protocol",
  },
  babylon: {
    name: "Babylon Protocol",
    slug: "babylon-protocol",
  },
  tethergold: {
    name: "Tether Gold",
    slug: "tether-gold",
  },
  tether: {
    name: "Tether Gold",
    slug: "tether-gold",
  },
  steakhousefinancial: {
    name: "Steakhouse Financial",
    slug: "steakhouse-financial",
  },
  steakhouse: {
    name: "Steakhouse Financial",
    slug: "steakhouse-financial",
  },
  maple: {
    name: "Maple",
    slug: "maple",
  },
  basebridge: {
    name: "Base Bridge",
    slug: "base-bridge",
  },
  base: {
    name: "Base Bridge",
    slug: "base-bridge",
  },
  spiko: {
    name: "Spiko",
    slug: "spiko",
  },
  circleusyc: {
    name: "Circle USYC",
    slug: "circle-usyc",
  },
  circle: {
    name: "Circle USYC",
    slug: "circle-usyc",
  },
  sparkliquiditylayer: {
    name: "Spark Liquidity Layer",
    slug: "spark-liquidity-layer",
  },
  spark: {
    name: "Spark Liquidity Layer",
    slug: "spark-liquidity-layer",
  },
  ondoyieldassets: {
    name: "Ondo Yield Assets",
    slug: "ondo-yield-assets",
  },
  ondo: {
    name: "Ondo Yield Assets",
    slug: "ondo-yield-assets",
  },
  sentoracurator: {
    name: "Sentora Curator",
    slug: "sentora-curator",
  },
  sentora: {
    name: "Sentora Curator",
    slug: "sentora-curator",
  },
  grovefinance: {
    name: "Grove Finance",
    slug: "grove-finance",
  },
  grove: {
    name: "Grove Finance",
    slug: "grove-finance",
  },
  pancakeswapamm: {
    name: "PancakeSwap",
    slug: "pancakeswap-amm",
  },
  pancakeswap: {
    name: "PancakeSwap",
    slug: "pancakeswap-amm",
  },
  paxosgold: {
    name: "Paxos Gold",
    slug: "paxos-gold",
  },
  paxos: {
    name: "Paxos Gold",
    slug: "paxos-gold",
  },
  veda: {
    name: "Veda",
    slug: "veda",
  },
  gauntlet: {
    name: "Gauntlet",
    slug: "gauntlet",
  },
  sanctumvalidatorlsts: {
    name: "Sanctum Validator LSTs",
    slug: "sanctum-validator-lsts",
  },
  sanctum: {
    name: "Sanctum Validator LSTs",
    slug: "sanctum-validator-lsts",
  },
  uniswapv3: {
    name: "Uniswap",
    slug: "uniswap-v3",
  },
  uniswap: {
    name: "Uniswap",
    slug: "uniswap-v3",
  },
  centrifugeprotocol: {
    name: "Centrifuge Protocol",
    slug: "centrifuge-protocol",
  },
  centrifuge: {
    name: "Centrifuge Protocol",
    slug: "centrifuge-protocol",
  },
  compoundv3: {
    name: "Compound",
    slug: "compound-v3",
  },
  compound: {
    name: "Compound",
    slug: "compound-v3",
  },
  rocketpool: {
    name: "Rocket Pool",
    slug: "rocket-pool",
  },
  rocket: {
    name: "Rocket Pool",
    slug: "rocket-pool",
  },
  kaminolend: {
    name: "Kamino",
    slug: "kamino-lend",
  },
  kamino: {
    name: "Kamino",
    slug: "kamino-lend",
  },
  curvedex: {
    name: "Curve",
    slug: "curve-dex",
  },
  curve: {
    name: "Curve",
    slug: "curve-dex",
  },
  venuscorepool: {
    name: "Venus Core Pool",
    slug: "venus-core-pool",
  },
  venus: {
    name: "Venus Core Pool",
    slug: "venus-core-pool",
  },
  sparksavings: {
    name: "Spark Savings",
    slug: "spark-savings",
  },
  pendlev2: {
    name: "Pendle",
    slug: "pendle-v2",
  },
  pendle: {
    name: "Pendle",
    slug: "pendle-v2",
  },
  wisdomtree: {
    name: "WisdomTree",
    slug: "wisdomtree",
  },
  concrete: {
    name: "Concrete",
    slug: "concrete",
  },
  falconfinance: {
    name: "Falcon Finance",
    slug: "falcon-finance",
  },
  falcon: {
    name: "Falcon Finance",
    slug: "falcon-finance",
  },
  kelp: {
    name: "Kelp",
    slug: "kelp",
  },
  raydiumamm: {
    name: "Raydium",
    slug: "raydium-amm",
  },
  raydium: {
    name: "Raydium",
    slug: "raydium-amm",
  },
  kinetiqkhype: {
    name: "Kinetiq kHYPE",
    slug: "kinetiq-khype",
  },
  kinetiq: {
    name: "Kinetiq kHYPE",
    slug: "kinetiq-khype",
  },
  uniswapv4: {
    name: "Uniswap",
    slug: "uniswap-v4",
  },
  jupiterlend: {
    name: "Jupiter",
    slug: "jupiter-lend",
  },
  jupiter: {
    name: "Jupiter",
    slug: "jupiter-lend",
  },
  binancestakedsol: {
    name: "Binance Staked SOL",
    slug: "binance-staked-sol",
  },
  jitoliquidstaking: {
    name: "Jito Liquid Staking",
    slug: "jito-liquid-staking",
  },
  jito: {
    name: "Jito Liquid Staking",
    slug: "jito-liquid-staking",
  },
  uniswapv2: {
    name: "Uniswap",
    slug: "uniswap-v2",
  },
  stakewisev3: {
    name: "StakeWise",
    slug: "stakewise-v3",
  },
  stakewise: {
    name: "StakeWise",
    slug: "stakewise-v3",
  },
  blockchaincapital: {
    name: "Blockchain Capital",
    slug: "blockchain-capital",
  },
  blockchain: {
    name: "Blockchain Capital",
    slug: "blockchain-capital",
  },
  ondoglobalmarkets: {
    name: "Ondo Global Markets",
    slug: "ondo-global-markets",
  },
  usdd: {
    name: "USDD",
    slug: "usdd",
  },
  listalending: {
    name: "Lista",
    slug: "lista-lending",
  },
  lista: {
    name: "Lista",
    slug: "lista-lending",
  },
  liquidcollective: {
    name: "Liquid Collective",
    slug: "liquid-collective",
  },
  liquid: {
    name: "Liquid Collective",
    slug: "liquid-collective",
  },
  robinhoodchainbridge: {
    name: "Robinhood Chain Bridge",
    slug: "robinhood-chain-bridge",
  },
  robinhood: {
    name: "Robinhood Chain Bridge",
    slug: "robinhood-chain-bridge",
  },
  tornadocash: {
    name: "Tornado Cash",
    slug: "tornado-cash",
  },
  tornado: {
    name: "Tornado Cash",
    slug: "tornado-cash",
  },
  listaliquidstaking: {
    name: "Lista Liquid Staking",
    slug: "lista-liquid-staking",
  },
  fluidlending: {
    name: "Fluid",
    slug: "fluid-lending",
  },
  fluid: {
    name: "Fluid",
    slug: "fluid-lending",
  },
  jupiterperpetualexchange: {
    name: "Jupiter Perpetual Exchange",
    slug: "jupiter-perpetual-exchange",
  },
  anemoycapital: {
    name: "Anemoy Capital",
    slug: "anemoy-capital",
  },
  anemoy: {
    name: "Anemoy Capital",
    slug: "anemoy-capital",
  },
  lombardlbtc: {
    name: "Lombard LBTC",
    slug: "lombard-lbtc",
  },
  lombard: {
    name: "Lombard LBTC",
    slug: "lombard-lbtc",
  },
  optimismbridge: {
    name: "Optimism Bridge",
    slug: "optimism-bridge",
  },
  optimism: {
    name: "Optimism Bridge",
    slug: "optimism-bridge",
  },
  methprotocol: {
    name: "mETH Protocol",
    slug: "meth-protocol",
  },
  meth: {
    name: "mETH Protocol",
    slug: "meth-protocol",
  },
  hastra: {
    name: "Hastra",
    slug: "hastra",
  },
  invescoustb: {
    name: "Invesco USTB",
    slug: "invesco-ustb",
  },
  invesco: {
    name: "Invesco USTB",
    slug: "invesco-ustb",
  },
  convexfinance: {
    name: "Convex Finance",
    slug: "convex-finance",
  },
  convex: {
    name: "Convex Finance",
    slug: "convex-finance",
  },
  hyperlendpooled: {
    name: "HyperLend Pooled",
    slug: "hyperlend-pooled",
  },
  hyperlend: {
    name: "HyperLend Pooled",
    slug: "hyperlend-pooled",
  },
  jupiterstakedsol: {
    name: "Jupiter Staked SOL",
    slug: "jupiter-staked-sol",
  },
  k3capital: {
    name: "K3 Capital",
    slug: "k3-capital",
  },
  k3: {
    name: "K3 Capital",
    slug: "k3-capital",
  },
  coinbasewrappedstakedeth: {
    name: "Coinbase Wrapped Staked ETH",
    slug: "coinbase-wrapped-staked-eth",
  },
  coinbase: {
    name: "Coinbase Wrapped Staked ETH",
    slug: "coinbase-wrapped-staked-eth",
  },
  ethenausdtb: {
    name: "Ethena USDtb",
    slug: "ethena-usdtb",
  },
  symbiotic: {
    name: "Symbiotic",
    slug: "symbiotic",
  },
  etherfiliquid: {
    name: "ether.fi Liquid",
    slug: "ether.fi-liquid",
  },
  upshift: {
    name: "Upshift",
    slug: "upshift",
  },
  aavev4: {
    name: "Aave",
    slug: "aave-v4",
  },
  worldchain: {
    name: "World Chain",
    slug: "world-chain",
  },
  world: {
    name: "World Chain",
    slug: "world-chain",
  },
  rocketswapanubis: {
    name: "RocketSwap Anubis",
    slug: "rocketswap-anubis",
  },
  rocketswap: {
    name: "RocketSwap Anubis",
    slug: "rocketswap-anubis",
  },
  polymarketinternational: {
    name: "Polymarket International",
    slug: "polymarket-international",
  },
  polymarket: {
    name: "Polymarket International",
    slug: "polymarket-international",
  },
  re: {
    name: "Re",
    slug: "re",
  },
  eulerv2: {
    name: "Euler",
    slug: "euler-v2",
  },
  euler: {
    name: "Euler",
    slug: "euler-v2",
  },
  defisaverassetmanagement: {
    name: "Defi Saver Asset Management",
    slug: "defi-saver-asset-management",
  },
  defi: {
    name: "Defi Saver Asset Management",
    slug: "defi-saver-asset-management",
  },
  tbtc: {
    name: "tBTC",
    slug: "tbtc",
  },
  cap: {
    name: "cap",
    slug: "cap",
  },
  pumpswap: {
    name: "PumpSwap",
    slug: "pumpswap",
  },
  pancakeswapammv3: {
    name: "PancakeSwap AMM",
    slug: "pancakeswap-amm-v3",
  },
  bedrockunibtc: {
    name: "Bedrock uniBTC",
    slug: "bedrock-unibtc",
  },
  bedrock: {
    name: "Bedrock uniBTC",
    slug: "bedrock-unibtc",
  },
  fluiddex: {
    name: "Fluid",
    slug: "fluid-dex",
  },
  dolomite: {
    name: "Dolomite",
    slug: "dolomite",
  },
  onre: {
    name: "OnRe",
    slug: "onre",
  },
  humafinancev2: {
    name: "Huma Finance",
    slug: "huma-finance-v2",
  },
  huma: {
    name: "Huma Finance",
    slug: "huma-finance-v2",
  },
  rockawayx: {
    name: "RockawayX",
    slug: "rockawayx",
  },
  lightningnetwork: {
    name: "Lightning Network",
    slug: "lightning-network",
  },
  lightning: {
    name: "Lightning Network",
    slug: "lightning-network",
  },
  usdai: {
    name: "USD AI",
    slug: "usd-ai",
  },
  usd: {
    name: "USD AI",
    slug: "usd-ai",
  },
  driftstakedsol: {
    name: "Drift Staked SOL",
    slug: "drift-staked-sol",
  },
  drift: {
    name: "Drift Staked SOL",
    slug: "drift-staked-sol",
  },
  cianyieldlayer: {
    name: "CIAN Yield Layer",
    slug: "cian-yield-layer",
  },
  cian: {
    name: "CIAN Yield Layer",
    slug: "cian-yield-layer",
  },
  xdaistakebridge: {
    name: "xDAI Stake Bridge",
    slug: "xdai-stake-bridge",
  },
  xdai: {
    name: "xDAI Stake Bridge",
    slug: "xdai-stake-bridge",
  },
  gtbtc: {
    name: "GTBTC",
    slug: "gtbtc",
  },
  etherfiborrowingmarket: {
    name: "EtherFi Borrowing Market",
    slug: "etherfi-borrowing-market",
  },
  stader: {
    name: "Stader",
    slug: "stader",
  },
  mellowcore: {
    name: "Mellow Core",
    slug: "mellow-core",
  },
  mellow: {
    name: "Mellow Core",
    slug: "mellow-core",
  },
  opentrade: {
    name: "OpenTrade",
    slug: "opentrade",
  },
  sunswapv2: {
    name: "SUNSwap",
    slug: "sunswap-v2",
  },
  sunswap: {
    name: "SUNSwap",
    slug: "sunswap-v2",
  },
  hyperithm: {
    name: "Hyperithm",
    slug: "hyperithm",
  },
  aavehorizonrwa: {
    name: "Aave Horizon RWA",
    slug: "aave-horizon-rwa",
  },
  orcadex: {
    name: "Orca",
    slug: "orca-dex",
  },
  orca: {
    name: "Orca",
    slug: "orca-dex",
  },
  b14g: {
    name: "b14g",
    slug: "b14g",
  },
  buzzfarming: {
    name: "Buzz Farming",
    slug: "buzz-farming",
  },
  buzz: {
    name: "Buzz Farming",
    slug: "buzz-farming",
  },
  openedentbill: {
    name: "OpenEden TBILL",
    slug: "openeden-tbill",
  },
  openeden: {
    name: "OpenEden TBILL",
    slug: "openeden-tbill",
  },
  lineabridge: {
    name: "Linea Bridge",
    slug: "linea-bridge",
  },
  linea: {
    name: "Linea Bridge",
    slug: "linea-bridge",
  },
  marinadeliquidstaking: {
    name: "Marinade Liquid Staking",
    slug: "marinade-liquid-staking",
  },
  marinade: {
    name: "Marinade Liquid Staking",
    slug: "marinade-liquid-staking",
  },
};
